language: php

php:
  - 5.5

before_script:
  - composer install --dev --no-interaction --prefer-source

script:
  - php vendor/squizlabs/php_codesniffer/scripts/phpcs --ignore=/Views/ --standard=PSR2 --report=summary --extensions=php public/ src/